export class User {
    constructor(
        public id:                  string,
        public role:                string,
        public name:                string,
        public last_name:           string,
        public second_last_name:    string,
        public gender:              string,
        public birthday:            string,
        public nationality:         string,
        public curp:                string,
        public admission_date:      string,
        public insurance:           string,
        public email:               string,
        public phone:               number,
        public outdoor_number:      number,
        public interior_number:     string,
        public street:              string,
        public locality:            string,
        public neighborhood:        string,
        public postal_code:         number,
        public current_township_id: number,
        public birthday_place:      number,
        public rfc:                 string,
        public status:              string,
        public password:            string,
    ){}
}